package net.hermajan.lyrics;

import java.awt.Desktop;
import java.awt.Font;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.Properties;
import javax.swing.text.html.HTMLDocument;
import net.hermajan.lyrics.providers.KaraokeTexty;
import net.hermajan.lyrics.providers.LyricWiki;
import net.hermajan.lyrics.providers.MetroLyrics;
import net.hermajan.lyrics.providers.Provider;

/**
 * GUI (Graphical user interface) for the application.
 * @author DJohnny
 */
public class GUI extends javax.swing.JFrame {
    private static final long serialVersionUID=1L;
    private final Properties prop=Settings.loadProperties();
    
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        usernameField.setText(prop.getProperty("username"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        providers = new javax.swing.ButtonGroup();
        lyricTab = new javax.swing.JTabbedPane();
        lyricPanel = new javax.swing.JPanel();
        artistLabel = new javax.swing.JLabel();
        artistField = new javax.swing.JTextField();
        trackLabel = new javax.swing.JLabel();
        trackField = new javax.swing.JTextField();
        urlLabel = new javax.swing.JLabel();
        urlField = new javax.swing.JTextField();
        providerLabel = new javax.swing.JLabel();
        lyricWikiButton = new javax.swing.JRadioButton();
        metroLyricsButton = new javax.swing.JRadioButton();
        getLyricsButton = new javax.swing.JButton();
        lastfmCheckBox = new javax.swing.JCheckBox();
        textScrollPane = new javax.swing.JScrollPane();
        lyricsText = new javax.swing.JEditorPane();
        karaokeTextyButton = new javax.swing.JRadioButton();
        urlOpenButton = new javax.swing.JButton();
        lastfmPanel = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        lastfmUrlField = new javax.swing.JTextField();
        lastfmUrlLabel = new javax.swing.JLabel();
        lastfmUrlOpenButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lyrics");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(500, 600));
        setResizable(false);

        lyricTab.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        lyricTab.setToolTipText("");
        lyricTab.setPreferredSize(new java.awt.Dimension(495, 595));

        lyricPanel.setMaximumSize(new java.awt.Dimension(470, 580));
        lyricPanel.setPreferredSize(new java.awt.Dimension(470, 580));

        artistLabel.setLabelFor(artistField);
        artistLabel.setText("Artist:");

        artistField.setToolTipText("");
        artistField.setPreferredSize(new java.awt.Dimension(445, 20));

        trackLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        trackLabel.setLabelFor(trackField);
        trackLabel.setText("Track:");

        trackField.setPreferredSize(new java.awt.Dimension(445, 20));

        urlLabel.setLabelFor(urlField);
        urlLabel.setText("URL:");
        urlLabel.setToolTipText("Uniform resource locator");

        urlField.setEditable(false);
        urlField.setDoubleBuffered(true);
        urlField.setMaximumSize(new java.awt.Dimension(380, 20));
        urlField.setPreferredSize(new java.awt.Dimension(450, 20));

        providerLabel.setText("Provider:");

        providers.add(lyricWikiButton);
        lyricWikiButton.setSelected(true);
        lyricWikiButton.setText("Lyric Wiki");

        providers.add(metroLyricsButton);
        metroLyricsButton.setText("MetroLyrics");
        metroLyricsButton.setMargin(new java.awt.Insets(0, 2, 0, 2));

        getLyricsButton.setText("Get lyrics");
        getLyricsButton.setPreferredSize(new java.awt.Dimension(100, 23));
        getLyricsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getLyricsButtonActionPerformed(evt);
            }
        });

        lastfmCheckBox.setText("Last.fm");

        textScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        textScrollPane.setAutoscrolls(true);
        textScrollPane.setPreferredSize(new java.awt.Dimension(369, 462));

        lyricsText.setContentType("text/html"); // NOI18N
        lyricsText.setFont(lyricsText.getFont());
        lyricsText.setToolTipText("");
        lyricsText.setDoubleBuffered(true);
        lyricsText.setMaximumSize(new java.awt.Dimension(350, 440));
        lyricsText.setName(""); // NOI18N
        lyricsText.setPreferredSize(new java.awt.Dimension(350, 460));
        lyricsText.setVerifyInputWhenFocusTarget(false);
        textScrollPane.setViewportView(lyricsText);

        providers.add(karaokeTextyButton);
        karaokeTextyButton.setText("Karaoke texty");
        karaokeTextyButton.setMargin(new java.awt.Insets(0, 2, 0, 2));

        urlOpenButton.setText("Open");
        urlOpenButton.setPreferredSize(new java.awt.Dimension(100, 23));
        urlOpenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urlOpenButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lyricPanelLayout = new javax.swing.GroupLayout(lyricPanel);
        lyricPanel.setLayout(lyricPanelLayout);
        lyricPanelLayout.setHorizontalGroup(
            lyricPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lyricPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(lyricPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lyricPanelLayout.createSequentialGroup()
                        .addComponent(textScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(lyricPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lyricPanelLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(lyricPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(metroLyricsButton)
                                    .addComponent(lyricWikiButton)
                                    .addComponent(karaokeTextyButton)
                                    .addComponent(lastfmCheckBox)
                                    .addComponent(providerLabel)))
                            .addGroup(lyricPanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(getLyricsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(lyricPanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(urlOpenButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(lyricPanelLayout.createSequentialGroup()
                        .addComponent(urlLabel)
                        .addGap(5, 5, 5)
                        .addComponent(urlField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(lyricPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(lyricPanelLayout.createSequentialGroup()
                            .addComponent(trackLabel)
                            .addGap(5, 5, 5)
                            .addComponent(trackField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(lyricPanelLayout.createSequentialGroup()
                            .addComponent(artistLabel)
                            .addGap(5, 5, 5)
                            .addComponent(artistField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(5, 5, 5))
        );
        lyricPanelLayout.setVerticalGroup(
            lyricPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lyricPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(lyricPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(artistLabel)
                    .addComponent(artistField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(lyricPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trackField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trackLabel))
                .addGap(5, 5, 5)
                .addGroup(lyricPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(urlField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(urlLabel))
                .addGap(5, 5, 5)
                .addGroup(lyricPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lyricPanelLayout.createSequentialGroup()
                        .addComponent(urlOpenButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(providerLabel)
                        .addGap(0, 0, 0)
                        .addComponent(karaokeTextyButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lyricWikiButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(metroLyricsButton)
                        .addGap(15, 15, 15)
                        .addComponent(lastfmCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(getLyricsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(textScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        lyricTab.addTab("Lyric", lyricPanel);

        lastfmPanel.setPreferredSize(new java.awt.Dimension(470, 590));

        usernameLabel.setText("Username:");

        usernameField.setPreferredSize(new java.awt.Dimension(340, 20));

        saveButton.setText("Save");
        saveButton.setPreferredSize(new java.awt.Dimension(70, 23));
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        lastfmUrlField.setEditable(false);
        lastfmUrlField.setDoubleBuffered(true);
        lastfmUrlField.setMaximumSize(new java.awt.Dimension(450, 20));
        lastfmUrlField.setPreferredSize(new java.awt.Dimension(450, 20));

        lastfmUrlLabel.setLabelFor(urlField);
        lastfmUrlLabel.setText("URL of the song:");
        lastfmUrlLabel.setToolTipText("Uniform resource locator");

        lastfmUrlOpenButton.setText("Open");
        lastfmUrlOpenButton.setToolTipText("");
        lastfmUrlOpenButton.setPreferredSize(new java.awt.Dimension(100, 23));
        lastfmUrlOpenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastfmUrlOpenButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lastfmPanelLayout = new javax.swing.GroupLayout(lastfmPanel);
        lastfmPanel.setLayout(lastfmPanelLayout);
        lastfmPanelLayout.setHorizontalGroup(
            lastfmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lastfmPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(lastfmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lastfmPanelLayout.createSequentialGroup()
                        .addComponent(usernameLabel)
                        .addGap(5, 5, 5)
                        .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lastfmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lastfmUrlField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(lastfmPanelLayout.createSequentialGroup()
                            .addComponent(lastfmUrlLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lastfmUrlOpenButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(5, 5, 5))
        );
        lastfmPanelLayout.setVerticalGroup(
            lastfmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lastfmPanelLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(lastfmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameLabel)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(lastfmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastfmUrlLabel)
                    .addComponent(lastfmUrlOpenButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(lastfmUrlField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(495, Short.MAX_VALUE))
        );

        lyricTab.addTab("Last.fm", lastfmPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lyricTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lyricTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getLyricsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getLyricsButtonActionPerformed
        Lastfm lf=new Lastfm("");
		if(lastfmCheckBox.isSelected()) {
            lf.setUsername(usernameField.getText());
            artistField.setText(lf.getArtist()); trackField.setText(lf.getTrack());
        }
		lastfmUrlField.setText(lf.getURL());
        
        Provider lyric=new LyricWiki(artistField.getText(),trackField.getText());
        if(karaokeTextyButton.isSelected()==true) { 
            lyric=new KaraokeTexty(artistField.getText(),trackField.getText());
        }
        if(lyricWikiButton.isSelected()==true) { 
            lyric=new LyricWiki(artistField.getText(),trackField.getText());
        }
        if(metroLyricsButton.isSelected()==true) { 
            lyric=new MetroLyrics(artistField.getText(),trackField.getText());
        }
        
        urlField.setText(lyric.getURL());
        lyricsText.setText(lyric.parsing());
        
        // Sets a default rendering font type.
        Font font=lyricsText.getFont();
        String settingFont="body { font-family: "+font.getFamily()+"; "+"font-size: "+font.getSize()+"pt; }";
        ((HTMLDocument)lyricsText.getDocument()).getStyleSheet().addRule(settingFont);
    }//GEN-LAST:event_getLyricsButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
    	Settings.saveProperty("username",usernameField.getText());
        
        if(lastfmCheckBox.isSelected()==true) { getLyricsButton.doClick(); }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void urlOpenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urlOpenButtonActionPerformed
        try {
            Desktop.getDesktop().browse(new URI(urlField.getText()));
        } catch(URISyntaxException|IOException ex) {
            System.err.println(ex);
        }
    }//GEN-LAST:event_urlOpenButtonActionPerformed

    private void lastfmUrlOpenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastfmUrlOpenButtonActionPerformed
        try {
            Desktop.getDesktop().browse(new URI(lastfmUrlField.getText()));
        } catch(URISyntaxException|IOException ex) {
            System.err.println(ex);
        }
    }//GEN-LAST:event_lastfmUrlOpenButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField artistField;
    private javax.swing.JLabel artistLabel;
    private javax.swing.JButton getLyricsButton;
    private javax.swing.JRadioButton karaokeTextyButton;
    private javax.swing.JCheckBox lastfmCheckBox;
    private javax.swing.JPanel lastfmPanel;
    private javax.swing.JTextField lastfmUrlField;
    private javax.swing.JLabel lastfmUrlLabel;
    private javax.swing.JButton lastfmUrlOpenButton;
    private javax.swing.JPanel lyricPanel;
    private javax.swing.JTabbedPane lyricTab;
    private javax.swing.JRadioButton lyricWikiButton;
    private javax.swing.JEditorPane lyricsText;
    private javax.swing.JRadioButton metroLyricsButton;
    private javax.swing.JLabel providerLabel;
    private javax.swing.ButtonGroup providers;
    private javax.swing.JButton saveButton;
    private javax.swing.JScrollPane textScrollPane;
    private javax.swing.JTextField trackField;
    private javax.swing.JLabel trackLabel;
    private javax.swing.JTextField urlField;
    private javax.swing.JLabel urlLabel;
    private javax.swing.JButton urlOpenButton;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
